import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { ArrowLeft, ChevronUp } from "lucide-react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import OperationMap from "../../maps/OperationMap";
import { cn } from "../../../lib/utils";
const CreateOperationStep = ({ title = "Create Operation", operationName, setOperationName, latitude, setLatitude, longitude, setLongitude, radius, setRadius, dailyGoal, setDailyGoal, maxSpeed, setMaxSpeed, swellFactor, setSwellFactor, totalMaterial, setTotalMaterial, polygon, setPolygon, onNext, onBack, isExpanded = true, onToggleExpand, }) => {
    return (_jsxs("div", { className: "glass-card rounded-xl overflow-hidden animate-slide-up", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-border/50 cursor-pointer hover:bg-secondary/30 transition-colors", onClick: onToggleExpand, children: [_jsx("h2", { className: "text-lg font-display font-semibold", children: title }), _jsx(ChevronUp, { className: cn("w-5 h-5 text-muted-foreground transition-transform duration-300", !isExpanded && "rotate-180") })] }), isExpanded && (_jsxs("div", { className: "p-6 space-y-6", children: [onBack && (_jsxs(Button, { variant: "outline", size: "sm", onClick: onBack, className: "gap-2", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "Back"] })), _jsx(Input, { label: "Operation Name", placeholder: "Enter operation name", value: operationName, onChange: (e) => setOperationName(e.target.value) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx(Input, { label: "Latitude", placeholder: "Latitude", value: latitude, onChange: (e) => setLatitude(e.target.value), type: "number" }), _jsx(Input, { label: "Longitude", placeholder: "Longitude", value: longitude, onChange: (e) => setLongitude(e.target.value), type: "number" }), _jsx(Input, { label: "Radius (meters)", placeholder: "0", value: radius, onChange: (e) => setRadius(e.target.value), type: "number" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "text-sm font-medium text-muted-foreground", children: "Operation Area" }), _jsx(OperationMap, { height: "350px", onPolygonChange: setPolygon, existingPolygon: polygon, drawMode: "polygon" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Input, { label: "Daily volume goal to move (m\u00B3)", placeholder: "Daily volume goal to move m3", value: dailyGoal, onChange: (e) => setDailyGoal(e.target.value), type: "number" }), _jsx(Input, { label: "Operation Max Speed (km/h)", placeholder: "Operation Max Speed (km/h)", value: maxSpeed, onChange: (e) => setMaxSpeed(e.target.value), type: "number" })] }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-2 gap-4", children: [_jsx(Input, { label: "Operation material swell factor %", placeholder: "Operation material swell factor %", value: swellFactor, onChange: (e) => setSwellFactor(e.target.value), type: "number" }), _jsx(Input, { label: "Operation total material to move in bank (m\u00B3)", placeholder: "Operation total material to move in bank m3", value: totalMaterial, onChange: (e) => setTotalMaterial(e.target.value), type: "number" })] }), _jsx(Button, { onClick: onNext, className: "w-full", size: "xl", children: "Next" })] }))] }));
};
export default CreateOperationStep;
