import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React, { useState } from "react";
import { ArrowLeft, ChevronUp, Search } from "lucide-react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import { cn } from "../../../lib/utils";
const DeviceAssignmentStep = ({ operationName, devices, onAssign, onNext, onBack, isExpanded = true, onToggleExpand, }) => {
    const [searchQuery, setSearchQuery] = useState("");
    const filteredDevices = devices.filter((device) => device.name.toLowerCase().includes(searchQuery.toLowerCase()));
    return (_jsxs("div", { className: "glass-card rounded-xl overflow-hidden animate-slide-up", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-border/50 cursor-pointer hover:bg-secondary/30 transition-colors", onClick: onToggleExpand, children: [_jsxs("div", { className: "flex items-center gap-3", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: (e) => { e.stopPropagation(); onBack(); }, className: "gap-2", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "Back"] }), _jsxs("h2", { className: "text-lg font-display font-semibold", children: ["Assign Devices to Operation: ", operationName] })] }), _jsx(ChevronUp, { className: cn("w-5 h-5 text-muted-foreground transition-transform duration-300", !isExpanded && "rotate-180") })] }), isExpanded && (_jsxs("div", { className: "p-6 space-y-6", children: [_jsxs("div", { className: "relative", children: [_jsx(Search, { className: "absolute left-4 top-1/2 -translate-y-1/2 w-4 h-4 text-muted-foreground" }), _jsx(Input, { placeholder: "Search device by name...", value: searchQuery, onChange: (e) => setSearchQuery(e.target.value), className: "pl-11" })] }), _jsx("div", { className: "space-y-3 max-h-[400px] overflow-y-auto pr-2", children: filteredDevices.map((device, index) => (_jsxs("div", { className: cn("flex items-center justify-between px-5 py-4 rounded-xl border border-border/50 bg-secondary/30", "hover:bg-secondary/50 hover:border-primary/30 transition-all duration-200", "animate-fade-in", device.assigned && "border-success/50 bg-success/10"), style: { animationDelay: `${index * 30}ms` }, children: [_jsxs("div", { className: "flex flex-col gap-1", children: [_jsx("span", { className: "font-semibold text-foreground", children: device.name }), _jsxs("span", { className: "text-xs text-muted-foreground", children: ["Flespi ID: ", device.flespiId] })] }), _jsx(Button, { variant: device.assigned ? "success" : "default", size: "sm", onClick: () => onAssign(device.id), children: device.assigned ? "Assigned" : "Assign" })] }, device.id))) }), _jsx(Button, { onClick: onNext, className: "w-full", size: "xl", children: "Next" })] }))] }));
};
export default DeviceAssignmentStep;
