import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import { ArrowLeft, ChevronUp } from "lucide-react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import OperationMap from "../../maps/OperationMap";
import { cn } from "../../../lib/utils";
const DumpAreaStep = ({ title = "Edit Dump Area", operationName, dumpAreaName, setDumpAreaName, latitude, setLatitude, longitude, setLongitude, radius, setRadius, maxTime, setMaxTime, polygon, setPolygon, operationPolygon, zonePolygon, loadPadPolygon, onNext, onBack, isExpanded = true, onToggleExpand, }) => {
    return (_jsxs("div", { className: "glass-card rounded-xl overflow-hidden animate-slide-up", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-border/50 cursor-pointer hover:bg-secondary/30 transition-colors", onClick: onToggleExpand, children: [_jsxs("h2", { className: "text-lg font-display font-semibold", children: [title, operationName ? ` ${operationName}` : ""] }), _jsx(ChevronUp, { className: cn("w-5 h-5 text-muted-foreground transition-transform duration-300", !isExpanded && "rotate-180") })] }), isExpanded && (_jsxs("div", { className: "p-6 space-y-6", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: onBack, className: "gap-2", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "Back"] }), _jsx(Input, { label: "DUMP_AREA Name", placeholder: "Enter dump area name", value: dumpAreaName, onChange: (e) => setDumpAreaName(e.target.value) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx(Input, { label: "Latitude", placeholder: "Latitude", value: latitude, onChange: (e) => setLatitude(e.target.value), type: "number" }), _jsx(Input, { label: "Longitude", placeholder: "Longitude", value: longitude, onChange: (e) => setLongitude(e.target.value), type: "number" }), _jsx(Input, { label: "Radius (meters)", placeholder: "0", value: radius, onChange: (e) => setRadius(e.target.value), type: "number" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "text-sm font-medium text-muted-foreground", children: "Draw Dump Area (inside Operation geometry)" }), _jsx(OperationMap, { height: "350px", onPolygonChange: setPolygon, existingPolygon: polygon, circleCenter: latitude && longitude ? [Number(longitude), Number(latitude)] : null, circleRadiusMeters: radius ? Number(radius) : null, restrictionPolygon: operationPolygon, referencePolygon: operationPolygon, referencePolygons: [operationPolygon, zonePolygon, loadPadPolygon].filter(Boolean), referencePolygonColors: ["#22d3ee", "#22c55e", "#f97316"], drawMode: "polygon" })] }), _jsx(Input, { label: "Vehicle maximum time inside DUMP_AREA / to activate an alert", placeholder: "Maximum time in minutes", value: maxTime, onChange: (e) => setMaxTime(e.target.value), type: "number" }), _jsx(Button, { onClick: onNext, className: "w-full", size: "xl", children: "Next" })] }))] }));
};
export default DumpAreaStep;

