import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import React from "react";
import { ArrowLeft, ChevronUp } from "lucide-react";
import { Button } from "../../ui/button";
import { Input } from "../../ui/input";
import OperationMap from "../../maps/OperationMap";
import { cn } from "../../../lib/utils";
const ZoneAreaStep = ({ title = "Edit Zone Area", operationName, zoneName, setZoneName, latitude, setLatitude, longitude, setLongitude, radius, setRadius, swellFactor, setSwellFactor, totalMaterial, setTotalMaterial, maxSpeed, setMaxSpeed, polygon, setPolygon, operationPolygon, onNext, onBack, isExpanded = true, onToggleExpand, }) => {
    return (_jsxs("div", { className: "glass-card rounded-xl overflow-hidden animate-slide-up", children: [_jsxs("div", { className: "flex items-center justify-between px-6 py-4 border-b border-border/50 cursor-pointer hover:bg-secondary/30 transition-colors", onClick: onToggleExpand, children: [_jsxs("h2", { className: "text-lg font-display font-semibold", children: [title, operationName ? ` ${operationName}` : ""] }), _jsx(ChevronUp, { className: cn("w-5 h-5 text-muted-foreground transition-transform duration-300", !isExpanded && "rotate-180") })] }), isExpanded && (_jsxs("div", { className: "p-6 space-y-6", children: [_jsxs(Button, { variant: "outline", size: "sm", onClick: onBack, className: "gap-2", children: [_jsx(ArrowLeft, { className: "w-4 h-4" }), "Back"] }), _jsx(Input, { label: "Zone Area Name", placeholder: "Enter zone name", value: zoneName, onChange: (e) => setZoneName(e.target.value) }), _jsxs("div", { className: "grid grid-cols-1 md:grid-cols-3 gap-4", children: [_jsx(Input, { label: "Latitude", placeholder: "Latitude", value: latitude, onChange: (e) => setLatitude(e.target.value), type: "number" }), _jsx(Input, { label: "Longitude", placeholder: "Longitude", value: longitude, onChange: (e) => setLongitude(e.target.value), type: "number" }), _jsx(Input, { label: "Radius (meters)", placeholder: "0", value: radius, onChange: (e) => setRadius(e.target.value), type: "number" })] }), _jsxs("div", { className: "space-y-3", children: [_jsx("h3", { className: "text-sm font-medium text-muted-foreground", children: "Draw Zone Area (inside Operation geometry)" }), _jsx(OperationMap, { height: "350px", onPolygonChange: setPolygon, existingPolygon: polygon, restrictionPolygon: operationPolygon, referencePolygons: [operationPolygon].filter(Boolean), referencePolygonColors: ["#14b8a6"], drawMode: "polygon" })] }), _jsx(Input, { label: "Zone material swell factor %", placeholder: "Zone material swell factor %", value: swellFactor, onChange: (e) => setSwellFactor(e.target.value), type: "number" }), _jsx(Input, { label: "Zone total material to move in bank (m\u00B3)", placeholder: "Zone total material to move in bank m3", value: totalMaterial, onChange: (e) => setTotalMaterial(e.target.value), type: "number" }), _jsx(Input, { label: "Vehicles max speed in km/h (replaces operation max speed)", placeholder: "Vehicles max speed in km/h", value: maxSpeed, onChange: (e) => setMaxSpeed(e.target.value), type: "number" }), _jsx(Button, { onClick: onNext, className: "w-full", size: "xl", children: "Next" })] }))] }));
};
export default ZoneAreaStep;
