export const rimacFormSections = [
  {
    title: "Service Details",
    fields: [
      { name: "serviceStartDate", placeholder: "Service start date" },
      { name: "serviceEndDate", placeholder: "Service end date" },
      { name: "serviceStartTime", placeholder: "Service start time" },
      { name: "serviceEndTime", placeholder: "Service end time" },
      { name: "serviceLocation", placeholder: "Service location" },
      { name: "district", placeholder: "District" },
      { name: "policeStation", placeholder: "Police station" },
      { name: "incidentType", placeholder: "Incident type" },
      { name: "responsibility", placeholder: "Responsibility" },
      { name: "agreement", placeholder: "Agreement" },
      { name: "campaignApplies", placeholder: "Campaign applies?" },
      { name: "couponDelivered", placeholder: "Coupon delivered?" },
      { name: "possibleTotalLoss", placeholder: "Possible total loss?" },
      { name: "deathsOrInjuries", placeholder: "Deaths or injuries?" },
      { name: "hasCamera", placeholder: "Has camera?" },
      { name: "computerTheft", placeholder: "Computer theft?" },
      { name: "hasWitness", placeholder: "Has witness?" },
      { name: "hasTrafficLight", placeholder: "Has traffic light?" },
    ],
  },
  {
    title: "Insured Information",
    fields: [
      { name: "insuredFullName", placeholder: "Full name of insured" },
      { name: "insuredEmail", placeholder: "Email of insured" },
      { name: "insuredPhone", placeholder: "Phone of insured" },
    ],
  },
  {
    title: "Driver Information",
    fields: [
      { name: "driverFirstName", placeholder: "First name" },
      { name: "driverLastNamePaternal", placeholder: "Paternal surname" },
      { name: "driverLastNameMaternal", placeholder: "Maternal surname" },
      { name: "driverAge", placeholder: "Age" },
      { name: "driverDocumentType", placeholder: "Document type" },
      { name: "driverDocumentNumber", placeholder: "Document number" },
      { name: "driverLicense", placeholder: "License number" },
      { name: "driverLicenseCategory", placeholder: "License category" },
      { name: "driverLicenseValidity", placeholder: "License validity" },
      { name: "driverPhone", placeholder: "Phone number" },
      { name: "driverAlcoholTest", placeholder: "Alcohol test result" },
      { name: "driverHospital", placeholder: "Hospital info" },
    ],
  },
  {
    title: "Vehicle Information",
    fields: [
      { name: "vehiclePlate", placeholder: "Vehicle plate" },
      { name: "vehicleYear", placeholder: "Vehicle year" },
      { name: "vehicleMileage", placeholder: "Vehicle mileage" },
      { name: "vehicleUsage", placeholder: "Vehicle usage" },
      { name: "vehicleDamages", placeholder: "Vehicle damages" },
    ],
  },
  {
    title: "Injuries & Deaths",
    fields: [
      { name: "insuredDeaths", placeholder: "Insured deaths" },
      { name: "thirdPartyDeaths", placeholder: "Third-party deaths" },
      { name: "insuredInjuries", placeholder: "Insured injuries" },
      { name: "thirdPartyInjuries", placeholder: "Third-party injuries" },
    ],
  },
  {
    title: "Analysis",
    fields: [{ name: "analysis", placeholder: "Incident analysis" }],
  },
  {
    title: "Police Report",
    fields: [{ name: "policeReport", placeholder: "Police report" }],
  },
  {
    title: "On-Site Inspection",
    fields: [
      { name: "roadName", placeholder: "Road name" },
      { name: "roadType", placeholder: "Road type" },
      { name: "roadway", placeholder: "Roadway" },
      { name: "roadCondition", placeholder: "Road condition" },
      { name: "lanes", placeholder: "Number of lanes" },
      { name: "centralDivider", placeholder: "Central divider" },
      { name: "orientation", placeholder: "Road orientation" },
      { name: "configuration", placeholder: "Configuration" },
      { name: "vehicleFlow", placeholder: "Vehicle flow" },
      { name: "trafficIntensity", placeholder: "Traffic intensity" },
      { name: "lighting", placeholder: "Lighting" },
      { name: "environment", placeholder: "Environment" },
      { name: "visibility", placeholder: "Visibility" },
      { name: "regulatorySigns", placeholder: "Regulatory signs" },
      { name: "restrictions", placeholder: "Restrictions" },
      { name: "details", placeholder: "Details" },
    ],
  },
  {
    title: "Participants",
    fields: [
      { name: "participantPlate", placeholder: "Plate" },
      { name: "participantType", placeholder: "Type" },
      { name: "participantFirstName", placeholder: "First name" },
      { name: "participantLastNamePaternal", placeholder: "Paternal surname" },
      { name: "participantLastNameMaternal", placeholder: "Maternal surname" },
      { name: "participantAge", placeholder: "Age" },
      { name: "participantInjured", placeholder: "Injured?" },
      { name: "participantGender", placeholder: "Gender" },
      { name: "participantDocumentType", placeholder: "Document type" },
      { name: "participantDocumentNumber", placeholder: "Document number" },
      { name: "participantPhone", placeholder: "Phone number" },
      { name: "participantAlcoholTest", placeholder: "Alcohol test" },
      { name: "participantHospital", placeholder: "Hospital info" },
      { name: "participantDiagnosis", placeholder: "Diagnosis" },
    ],
  },
];

export const fullWidthFields = [
  "serviceLocation",
  "insuredFullName",
  "driverHospital",
  "details",
  "participantHospital",
];
export const textAreaFields = ["analysis", "policeReport"];
