import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import React from "react";
import { MapPin, Settings, AlertCircle, ExternalLink, Truck, Loader2 } from "lucide-react";
import { cn } from "../../lib/utils";
const VehiclePopup = ({ vehicle, onClose, onLocate, onSettings, onAlert, onDetails, }) => {
    return (_jsxs("div", { className: "bg-card border border-border rounded-lg shadow-xl p-4 min-w-[280px] animate-scale-in", children: [_jsxs("div", { className: "flex items-center gap-3 mb-3", children: [_jsx("div", { className: cn("w-10 h-10 rounded-full flex items-center justify-center", vehicle.type === "truck" ? "bg-primary/20" : "bg-amber-500/20"), children: vehicle.type === "truck" ? (_jsx(Truck, { className: "w-5 h-5 text-primary" })) : (_jsx(Loader2, { className: "w-5 h-5 text-amber-500" })) }), _jsxs("div", { children: [_jsx("h4", { className: "font-semibold text-foreground", children: vehicle.name }), _jsx("p", { className: "text-xs text-muted-foreground", children: vehicle.lastUpdate })] })] }), _jsxs("div", { className: "grid grid-cols-2 gap-x-4 gap-y-2 mb-4 text-sm", children: [_jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "\u26A1 Eff:" }), _jsxs("span", { className: cn("font-medium", vehicle.efficiency > 80 ? "text-green-400" :
                                    vehicle.efficiency > 50 ? "text-amber-400" : "text-red-400"), children: [vehicle.efficiency.toFixed(2), "%"] })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "\uD83D\uDD04 Trips:" }), _jsx("span", { className: "font-medium text-foreground", children: vehicle.trips })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "\u26FD Fuel/mA3:" }), _jsx("span", { className: "font-medium text-foreground", children: vehicle.fuelPerM3.toFixed(2) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "Vol (mA3):" }), _jsx("span", { className: "font-medium text-foreground", children: vehicle.volumeM3.toFixed(2) })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "Cycle:" }), _jsx("span", { className: "font-medium text-foreground", children: vehicle.cycleTime })] }), _jsxs("div", { className: "flex items-center gap-2", children: [_jsx("span", { className: "text-muted-foreground", children: "Queue:" }), _jsx("span", { className: "font-medium text-foreground", children: vehicle.queueTime })] })] }), _jsxs("div", { className: "flex items-center gap-2 pt-3 border-t border-border", children: [_jsx("button", { onClick: onLocate, className: "p-2 rounded-md hover:bg-accent transition-colors", title: "Locate on map", children: _jsx(MapPin, { className: "w-4 h-4 text-red-400" }) }), _jsx("button", { onClick: onSettings, className: "p-2 rounded-md hover:bg-accent transition-colors", title: "Settings", children: _jsx(Settings, { className: "w-4 h-4 text-primary" }) }), _jsx("button", { onClick: onAlert, className: "p-2 rounded-md hover:bg-accent transition-colors", title: "Alerts", children: _jsx(AlertCircle, { className: "w-4 h-4 text-amber-400" }) }), _jsx("button", { onClick: onDetails, className: "p-2 rounded-md hover:bg-accent transition-colors", title: "View details", children: _jsx(ExternalLink, { className: "w-4 h-4 text-muted-foreground" }) })] })] }));
};
export default VehiclePopup;
